spring.application.name=expense-dashboard-backend

# Server
server.port=8080

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/expensedb
spring.datasource.username=expenseuser
spring.datasource.password=expense@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false